Sprint1
ClevertecFrontendLab/sprint1-drumwarz pull request #1
Opened 2023-02-01 12:56 UTC by drumwarz

2023-02-01 13:00 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675256409/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675256409/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675256409/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675256409/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675256409/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675256409/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675256409/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675256409/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675256409/content-window.png)

2023-02-01 13:14 UTC, klichkovskiy requested changes

2023-02-01 13:14 UTC, klichkovskiy commented on src/pages/books/books-page.jsx
> +  // const books = data.map((item) => {
Удали весь закоментированный код по всему приложению

2023-02-01 13:14 UTC, klichkovskiy commented on src/pages/books/books-page.jsx
> +  <NavLink to="/book"><BookItem /></NavLink>
промапать

2023-02-01 13:14 UTC, klichkovskiy commented on src/pages/book-item/book-item.jsx
> +//   const { name, salary, onDelete, onToggleProp, increase, rise } = props;
удалить

2023-02-01 13:14 UTC, klichkovskiy commented on src/index.js
> +          <Route path='book' element={<AppMainBook />} />
Зачем два разных компонента? Сделай просто условие на картинке, что если ее нет - отрисовываем котика

2023-02-01 13:14 UTC, klichkovskiy commented on src/components/app-main-book/app-main-book.jsx
> +<div className="mainbook">
![image](https://user-images.githubusercontent.com/62481116/216052270-40c07d2b-d19b-494d-a99d-6fc7e0074acb.png)
сделай как в макете

2023-02-01 13:14 UTC, klichkovskiy commented on src/components/app-main-book/app-main-book.jsx
> +			<div className="mainbook__info info">
![image](https://user-images.githubusercontent.com/62481116/216052381-1fa15aea-73f6-441d-896c-6661774d7d33.png)
сделай отступ как в макете

2023-02-01 13:14 UTC, klichkovskiy commented on src/components/app-main-book/app-main-book.jsx
> +			<div className="mainbook__reviews reviews">
промапать
![image](https://user-images.githubusercontent.com/62481116/216052488-204807e5-1f5a-4e60-a9bb-0db400cfdc98.png)
сделай как в макете

2023-02-01 13:14 UTC, klichkovskiy commented on src/components/app-main-book/app-main-book.jsx
> +const AppMainBook = () => (
![image](https://user-images.githubusercontent.com/62481116/216052570-b02a1859-72c4-414d-8d24-b08528f0dbe0.png)
сделай как в макете

2023-02-01 13:14 UTC, klichkovskiy commented on src/components/app-main-book/app-main-book.jsx
> +<div className="mainbook">
![image](https://user-images.githubusercontent.com/62481116/216052665-ff753239-9c89-4b0e-827a-f49ca2d328d3.png)
серый фон на всю ширину экрана

2023-02-01 13:14 UTC, klichkovskiy commented on src/components/app-menu/app-menu.jsx
> +		<ul className="menu__items" >
промапать

2023-02-01 13:14 UTC, klichkovskiy commented on src/components/app-search/app-search.jsx
> +	<div className="search">
![image](https://user-images.githubusercontent.com/62481116/216052852-94de2bd0-f2bf-45d6-b2c0-9e59b3020e56.png)
иконку сделай
и отступы как в макете

2023-02-01 13:14 UTC, klichkovskiy commented on src/index.js
> +          <Route path='main' element={<MainPage />} />
![image](https://user-images.githubusercontent.com/62481116/216052997-5bf5a867-19fa-418a-a825-6583d36be317.png)
Эта кнопка должна быть активной

2023-02-02 20:39 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675370340/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675370340/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675370340/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675370340/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675370340/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675370340/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675370340/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675370340/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/drumwarz/1675370340/content-window.png)

2023-02-02 20:41 UTC, klichkovskiy approved these changes

2023-02-02 20:43 UTC, merged